// 星图中文翻译数据
// domain: "skyculture" — 星座英文名 → 中文
// domain: "sky" — 行星、恒星、深空天体、方位等
var ZH_CN = {

  // === 88 星座：拉丁名 + 英文名 → 中文 (skyculture domain) ===
  // 拉丁名（引擎实际传入的名称）
  "Aquila": "天鹰座",
  "Andromeda": "仙女座",
  "Sculptor": "玉夫座",
  "Ara": "天坛座",
  "Libra": "天秤座",
  "Cetus": "鲸鱼座",
  "Aries": "白羊座",
  "Scutum": "盾牌座",
  "Pyxis": "罗盘座",
  "Bootes": "牧夫座",
  "Caelum": "雕具座",
  "Chamaeleon": "蝘蜓座",
  "Cancer": "巨蟹座",
  "Capricornus": "摩羯座",
  "Carina": "船底座",
  "Cassiopeia": "仙后座",
  "Centaurus": "半人马座",
  "Cepheus": "仙王座",
  "Coma Berenices": "后发座",
  "Canes Venatici": "猎犬座",
  "Auriga": "御夫座",
  "Columba": "天鸽座",
  "Circinus": "圆规座",
  "Crater": "巨爵座",
  "Corona Australis": "南冕座",
  "Corona Borealis": "北冕座",
  "Corvus": "乌鸦座",
  "Crux": "南十字座",
  "Cygnus": "天鹅座",
  "Delphinus": "海豚座",
  "Dorado": "剑鱼座",
  "Draco": "天龙座",
  "Norma": "矩尺座",
  "Eridanus": "波江座",
  "Sagitta": "天箭座",
  "Fornax": "天炉座",
  "Gemini": "双子座",
  "Camelopardalis": "鹿豹座",
  "Canis Major": "大犬座",
  "Ursa Major": "大熊座",
  "Grus": "天鹤座",
  "Hercules": "武仙座",
  "Horologium": "时钟座",
  "Hydra": "长蛇座",
  "Hydrus": "水蛇座",
  "Indus": "印第安座",
  "Lacerta": "蝎虎座",
  "Monoceros": "麒麟座",
  "Lepus": "天兔座",
  "Leo": "狮子座",
  "Lupus": "豺狼座",
  "Lynx": "天猫座",
  "Lyra": "天琴座",
  "Antlia": "唧筒座",
  "Microscopium": "显微镜座",
  "Musca": "苍蝇座",
  "Octans": "南极座",
  "Apus": "天燕座",
  "Ophiuchus": "蛇夫座",
  "Orion": "猎户座",
  "Pavo": "孔雀座",
  "Pegasus": "飞马座",
  "Pictor": "绘架座",
  "Perseus": "英仙座",
  "Equuleus": "小马座",
  "Canis Minor": "小犬座",
  "Leo Minor": "小狮座",
  "Vulpecula": "狐狸座",
  "Ursa Minor": "小熊座",
  "Phoenix": "凤凰座",
  "Pisces": "双鱼座",
  "Piscis Austrinus": "南鱼座",
  "Volans": "飞鱼座",
  "Puppis": "船尾座",
  "Reticulum": "网罟座",
  "Sagittarius": "人马座",
  "Scorpius": "天蝎座",
  "Serpens": "巨蛇座",
  "Sextans": "六分仪座",
  "Mensa": "山案座",
  "Taurus": "金牛座",
  "Telescopium": "望远镜座",
  "Tucana": "杜鹃座",
  "Triangulum": "三角座",
  "Triangulum Australe": "南三角座",
  "Aquarius": "宝瓶座",
  "Virgo": "室女座",
  "Vela": "船帆座",
  // 英文名（备用）
  "Eagle": "天鹰座",
  "Chained Maiden": "仙女座",
  "Altar": "天坛座",
  "Scales": "天秤座",
  "Sea Monster": "鲸鱼座",
  "Ram": "白羊座",
  "Shield": "盾牌座",
  "Compass": "罗盘座",
  "Compasses": "圆规座",
  "Lyre": "天琴座",
  "Herdsman": "牧夫座",
  "Engraving Tool": "雕具座",
  "Chameleon": "蝘蜓座",
  "Crab": "巨蟹座",
  "Sea Goat": "摩羯座",
  "Keel": "船底座",
  "Seated Queen": "仙后座",
  "Centaur": "半人马座",
  "King": "仙王座",
  "Bernice's Hair": "后发座",
  "Hunting Dogs": "猎犬座",
  "Charioteer": "御夫座",
  "Dove": "天鸽座",
  "Cup": "巨爵座",
  "Southern Crown": "南冕座",
  "Northern Crown": "北冕座",
  "Crow": "乌鸦座",
  "Southern Cross": "南十字座",
  "Swan": "天鹅座",
  "Dolphin": "海豚座",
  "Swordfish": "剑鱼座",
  "Dragon": "天龙座",
  "Carpenter's Square": "矩尺座",
  "River": "波江座",
  "Arrow": "天箭座",
  "Furnace": "天炉座",
  "Twins": "双子座",
  "Giraffe": "鹿豹座",
  "Great Dog": "大犬座",
  "Great Bear": "大熊座",
  "Crane": "天鹤座",
  "Clock": "时钟座",
  "Female Water Snake": "长蛇座",
  "Male Water Snake": "水蛇座",
  "Indian": "印第安座",
  "Lizard": "蝎虎座",
  "Unicorn": "麒麟座",
  "Hare": "天兔座",
  "Lion": "狮子座",
  "Wolf": "豺狼座",
  "Air Pump": "唧筒座",
  "Microscope": "显微镜座",
  "Fly": "苍蝇座",
  "Octant": "南极座",
  "Bird of Paradise": "天燕座",
  "Serpent Bearer": "蛇夫座",
  "Hunter": "猎户座",
  "Peacock": "孔雀座",
  "Winged Horse": "飞马座",
  "Painter's Easel": "绘架座",
  "Hero": "英仙座",
  "Little Horse": "小马座",
  "Lesser Dog": "小犬座",
  "Lesser Lion": "小狮座",
  "Fox": "狐狸座",
  "Little Bear": "小熊座",
  "Fishes": "双鱼座",
  "Southern Fish": "南鱼座",
  "Flying Fish": "飞鱼座",
  "Stern": "船尾座",
  "Reticle": "网罟座",
  "Archer": "人马座",
  "Scorpion": "天蝎座",
  "Serpent": "巨蛇座",
  "Sextant": "六分仪座",
  "Table Mountain": "山案座",
  "Bull": "金牛座",
  "Telescope": "望远镜座",
  "Toucan": "杜鹃座",
  "Triangle": "三角座",
  "Southern Triangle": "南三角座",
  "Water Bearer": "宝瓶座",
  "Maiden": "室女座",
  "Sails": "船帆座",

  // === 行星 (sky domain) ===
  "Sun": "太阳",
  "Moon": "月亮",
  "Mercury": "水星",
  "Venus": "金星",
  "Mars": "火星",
  "Jupiter": "木星",
  "Saturn": "土星",
  "Uranus": "天王星",
  "Neptune": "海王星",
  "Pluto": "冥王星",
  "Earth": "地球",

  // === 方位 (sky domain) ===
  "N": "北",
  "S": "南",
  "E": "东",
  "W": "西",
  "NE": "东北",
  "NW": "西北",
  "SE": "东南",
  "SW": "西南",

  // === 主要恒星 (sky domain) ===
  "Sirius": "天狼星",
  "Canopus": "老人星",
  "Arcturus": "大角星",
  "Vega": "织女星",
  "Capella": "五车二",
  "Rigel": "参宿七",
  "Procyon": "南河三",
  "Betelgeuse": "参宿四",
  "Altair": "牛郎星",
  "Aldebaran": "毕宿五",
  "Antares": "心宿二",
  "Spica": "角宿一",
  "Pollux": "北河三",
  "Fomalhaut": "北落师门",
  "Deneb": "天津四",
  "Regulus": "轩辕十四",
  "Castor": "北河二",
  "Bellatrix": "参宿五",
  "Elnath": "五车五",
  "Alnilam": "参宿二",
  "Alnitak": "参宿一",
  "Mintaka": "参宿三",
  "Saiph": "参宿六",
  "Shaula": "尾宿八",
  "Dubhe": "天枢",
  "Alkaid": "摇光",
  "Merak": "天璇",
  "Phecda": "天玑",
  "Megrez": "天权",
  "Alioth": "玉衡",
  "Mizar": "开阳",
  "Alcor": "辅",
  "Polaris": "北极星",
  "Alpheratz": "壁宿二",
  "Mirach": "奎宿九",
  "Almach": "天大将军一",
  "Hamal": "娄宿三",
  "Schedar": "王良一",
  "Caph": "王良三",
  "Achernar": "水委一",
  "Algol": "大陵五",
  "Mira": "刍蒿增二",
  "Denebola": "五帝座一",
  "Rasalhague": "侯",
  "Markab": "室宿一",
  "Algenib": "壁宿一",
  "Eltanin": "天棓四",
  "Kochab": "帝星",
  "Zubenelgenubi": "氐宿一",
  "Zubeneschamali": "氐宿四",
  "Acrab": "房宿三",
  "Dschubba": "房宿一",
  "Sargas": "尾宿五",
  "Kaus Australis": "箕宿三",
  "Nunki": "斗宿四",
  "Thuban": "右枢",
  "Albireo": "辇道增七",
  "Acrux": "十字架二",
  "Mimosa": "十字架三",
  "Gacrux": "十字架一",
  "Wezen": "弧矢一",
  "Adhara": "弧矢七",
  "Naos": "弧矢增二十二",
  "Alphard": "星宿一",
  "Enif": "危宿三",
  "Sadr": "天津一",
  "Gienah": "轸宿一",
  "Alhena": "井宿三",
  "Ain": "毕宿四",
  "Alcyone": "昴宿六",
  "Atlas": "昴宿七",
  "Electra": "昴宿一",
  "Maia": "昴宿四",
  "Merope": "昴宿五",
  "Taygeta": "昴宿二",
  "Pleione": "昴宿增十二",
  "Unukalhai": "蛇心",


  // --- 补充：恒星中英文对照表（自动导入） ---
  "15 Leonis": "轩辕六",
  "46 Leonis": "长垣一",
  "48 Leonis": "长垣四",
  "51 Leonis": "少微四",
  "52 Leonis": "长垣二",
  "53 Leonis": "长垣三",
  "54 Leonis": "少微二",
  "58 Leonis": "灵台三",
  "59 Leonis": "灵台二",
  "67 Leonis": "少微一",
  "72 Leonis": "虎贲",
  "87 Leonis": "明堂三",
  "92 Leonis": "从官",
  "93 Leonis": "太子",
  "95 Leonis": "五帝座四",
  "Adhafera": "轩辕十一",
  "Al Asad": "轩辕七",
  "Al Jabhah": "轩辕十三",
  "Albali": "女宿一",
  "Alderamin": "天钩五",
  "Algenubi": "轩辕九",
  "Algieba": "轩辕十二",
  "Alnair": "鹤一",
  "Alniyat": "心宿一",
  "Alrescha": "外屏七",
  "Alterf": "轩辕八",
  "Aludra": "弧矢二",
  "Ankaa": "火鸟六",
  "Arkab Posterior": "天渊一",
  "Arkab Prior": "天渊二",
  "Arneb": "厕一",
  "Ascella": "斗宿六",
  "Atria": "三角形三",
  "Avior": "海石一",
  "Beta Gruis": "鹤二",
  "Beta Scorpii": "尾宿二",
  "Bharani": "胃宿三",
  "Botein": "天阴四",
  "Chertan": "太微右垣四/西次相",
  "Chi Leonis": "灵台一",
  "Diphda": "土司空",
  "Epsilon Centauri": "南门一",
  "Eta Centauri": "库楼二",
  "Gamma Cassiopeiae": "策",
  "Gemma": "贯索四",
  "Girtab": "尾宿七",
  "Graffias": "房宿四",
  "Grafias": "尾宿三",
  "HD 102103": "五帝座三",
  "HD 102660": "五帝座二",
  "HD 102910": "五帝座五",
  "HD 83069": "轩辕五",
  "Hadar": "马腹一",
  "Izar": "梗河一",
  "Jabah": "键闭",
  "Kaus Borealis": "斗宿二",
  "Kaus Media": "箕宿二",
  "Lambda Velorum": "天社五",
  "Lesath": "尾宿九",
  "Men": "骑官十",
  "Menkalinan": "五车三",
  "Menkar": "天囷一",
  "Menkent": "库楼三",
  "Mesartim / Mesarthim": "娄宿二",
  "Miaplacidus": "南船五",
  "Minchir": "太微右垣三/西次将",
  "Mirfak": "天船三",
  "Mirzam": "军市一",
  "Muhlifain": "库楼七",
  "Nu Leonis": "明堂二",
  "Nushaba": "箕宿一",
  "Omega Leonis": "酒旗三",
  "Phad": "天玑（北斗三）",
  "Phi Leonis": "明堂增六",
  "Pi Leonis": "轩辕十七/御女",
  "Pi Serpentis": "宋（天市左垣十一）",
  "Polis": "斗宿三",
  "Psi Leonis": "酒旗一",
  "Rasalas": "轩辕十",
  "Regor": "天社一",
  "Rigel Kentaurus": "南门二-A",
  "Sadachbia": "坟墓二",
  "Sadalmelik": "危宿一",
  "Sadalsuud": "虚宿一",
  "Samaka": "霹雳一",
  "Scheat": "室宿二",
  "Sheratan": "娄宿一",
  "Shir": "轩辕十六",
  "Sigma Leonis": "太微右垣二/西上将",
  "Skat": "羽林军二十六",
  "Subra": "轩辕十五",
  "Suhail": "天记",
  "Tau Leonis": "明堂一",
  "Xi Leonis": "酒旗二",
  "Zeta Centauri": "库楼一",
  "Zeta Ophiuchi": "韩",
  "Zosma": "西上相（太微右垣五）",

  // === 深空天体 (sky domain) ===
  "Crab Nebula": "蟹状星云",
  "Orion Nebula": "猎户座大星云",
  "Eagle Nebula": "鹰星云",
  "Omega Nebula": "欧米伽星云",
  "Lagoon Nebula": "礁湖星云",
  "Trifid Nebula": "三裂星云",
  "Ring Nebula": "环状星云",
  "Dumbbell Nebula": "哑铃星云",
  "Pinwheel Galaxy": "风车星系",
  "Whirlpool Galaxy": "涡状星系",
  "Andromeda Galaxy": "仙女座星系",
  "Triangulum Galaxy": "三角座星系",
  "Sombrero Galaxy": "草帽星系",
  "Bode's Galaxy": "波德星系",
  "Cigar Galaxy": "雪茄星系",
  "Sunflower Galaxy": "向日葵星系",
  "Black Eye Galaxy": "黑眼星系",
  "Centaurus A": "半人马座A",
  "Hercules Globular Cluster": "武仙座球状星团",
  "Great Star Cluster in Hercules": "武仙座球状星团",
  "Great Hercules Cluster": "武仙座球状星团",
  "Hercules Cluster": "武仙座球状星团",
  "Beehive Cluster": "蜂巢星团",
  "Praesepe": "蜂巢星团",
  "Pleiades": "昴星团",
  "Hyades": "毕星团",
  "Wild Duck Cluster": "野鸭星团",
  "Butterfly Cluster": "蝴蝶星团",
  "Ptolemy Cluster": "托勒密星团",
  "Double Cluster": "双星团",
  "Owl Nebula": "猫头鹰星云",
  "Helix Nebula": "螺旋星云",
  "Cat's Eye Nebula": "猫眼星云",
  "Horsehead Nebula": "马头星云",
  "Rosette Nebula": "玫瑰星云",
  "North America Nebula": "北美洲星云",
  "Veil Nebula": "面纱星云",
  "Cone Nebula": "锥状星云",
  "Flame Nebula": "火焰星云",
  "Pelican Nebula": "鹈鹕星云",
  "Carina Nebula": "船底座星云",
  "Tarantula Nebula": "蜘蛛星云",
  "Large Magellanic Cloud": "大麦哲伦云",
  "Small Magellanic Cloud": "小麦哲伦云",
  "Pegasus Cluster": "飞马座星团",
  "Sagittarius Star Cloud": "人马座星云",
  "Ptolemy's Cluster": "托勒密星团",
  "Southern Pinwheel Galaxy": "南风车星系",
  "Leo Triplet": "狮子座三重星系",
  "Sculptor Galaxy": "玉夫座星系",
  "Barnard's Galaxy": "巴纳德星系",
  "Spindle Galaxy": "纺锤星系",
  "Needle Galaxy": "针状星系",
  "Coathanger": "衣架星团",
  "Jewel Box": "珠宝盒星团",
  "47 Tucanae": "杜鹃座47",
  "Omega Centauri": "半人马座欧米伽",
  "Coal Sack": "煤袋星云",
  "Hourglass Region": "沙漏区域",
  "Taurus A": "金牛座A",
  "Swan Nebula": "天鹅星云",
  "Horseshoe Nebula": "马蹄星云",
  "Checkmark Nebula": "对勾星云",
  "Lobster Nebula": "龙虾星云",
  "Star Queen Nebula": "星之女王星云",
  "Dark Lane Galaxy": "暗带星系",
  "The Crucifix Cluster": "十字架星团",
  "Black Swan Cluster": "黑天鹅星团",


  // --- 补充：梅西耶天体（自动导入） ---
  "Little Dumbbell Nebula": "小哑铃星云",
  "M 1": "蟹状星云",
  "M 10": "球状星团M10",
  "M 100": "螺旋星系M100",
  "M 101": "风车星系",
  "M 102": "星系M102",
  "M 103": "疏散星团M103",
  "M 104": "草帽星系",
  "M 105": "椭圆星系M105",
  "M 106": "螺旋星系M106",
  "M 107": "球状星团M107",
  "M 108": "梭状星系M108",
  "M 109": "螺旋星系M109",
  "M 11": "野鸭星团",
  "M 110": "仙女座星系M110",
  "M 12": "球状星团M12",
  "M 13": "武仙座球状星团",
  "M 14": "球状星团M14",
  "M 15": "球状星团M15",
  "M 16": "鹰状星云",
  "M 17": "欧米茄星云",
  "M 18": "疏散星团M18",
  "M 19": "球状星团M19",
  "M 2": "球状星团M2",
  "M 20": "三叶星云",
  "M 21": "疏散星团M21",
  "M 22": "球状星团M22",
  "M 23": "疏散星团M23",
  "M 24": "小人马恒星云",
  "M 25": "疏散星团M25",
  "M 26": "疏散星团M26",
  "M 27": "哑铃星云",
  "M 28": "球状星团M28",
  "M 29": "疏散星团M29",
  "M 3": "球状星团M3",
  "M 30": "球状星团M30",
  "M 31": "仙女座星系",
  "M 32": "仙女座星系M32",
  "M 33": "三角座星系",
  "M 34": "疏散星团M34",
  "M 35": "疏散星团M35",
  "M 36": "疏散星团M36",
  "M 37": "疏散星团M37",
  "M 38": "疏散星团M38",
  "M 39": "疏散星团M39",
  "M 4": "球状星团M4",
  "M 40": "双星M40",
  "M 41": "疏散星团M41",
  "M 42": "猎户座大星云",
  "M 43": "猎户座M43",
  "M 44": "鬼星团",
  "M 45": "昴星团",
  "M 46": "疏散星团M46",
  "M 47": "疏散星团M47",
  "M 48": "疏散星团M48",
  "M 49": "室女座星系M49",
  "M 5": "球状星团M5",
  "M 50": "疏散星团M50",
  "M 51": "涡状星系",
  "M 52": "疏散星团M52",
  "M 53": "球状星团M53",
  "M 54": "球状星团M54",
  "M 55": "球状星团M55",
  "M 56": "球状星团M56",
  "M 57": "环状星云",
  "M 58": "室女座星系M58",
  "M 59": "室女座星系M59",
  "M 6": "蝴蝶星团",
  "M 60": "室女座星系M60",
  "M 61": "螺旋星系M61",
  "M 62": "球状星团M62",
  "M 63": "向日葵星系",
  "M 64": "黑眼星系",
  "M 65": "螺旋星系M65",
  "M 66": "螺旋星系M66",
  "M 67": "疏散星团M67",
  "M 68": "球状星团M68",
  "M 69": "球状星团M69",
  "M 7": "托勒密星团",
  "M 70": "球状星团M70",
  "M 71": "球状星团M71",
  "M 72": "球状星团M72",
  "M 73": "星群M73",
  "M 74": "螺旋星系M74",
  "M 75": "球状星团M75",
  "M 76": "小哑铃星云",
  "M 77": "螺旋星系M77",
  "M 78": "猎户座反射星云",
  "M 79": "球状星团M79",
  "M 8": "礁湖星云",
  "M 80": "球状星团M80",
  "M 81": "波德星系",
  "M 82": "雪茄星系",
  "M 83": "南风车星系",
  "M 84": "室女座星系M84",
  "M 85": "室女座星系M85",
  "M 86": "室女座星系M86",
  "M 87": "室女座星系M87",
  "M 88": "螺旋星系M88",
  "M 89": "室女座星系M89",
  "M 9": "球状星团M9",
  "M 90": "螺旋星系M90",
  "M 91": "螺旋星系M91",
  "M 92": "球状星团M92",
  "M 93": "疏散星团M93",
  "M 94": "螺旋星系M94",
  "M 95": "螺旋星系M95",
  "M 96": "螺旋星系M96",
  "M 97": "猫头鹰星云",
  "M 98": "螺旋星系M98",
  "M 99": "螺旋星系M99",
  "M1": "蟹状星云",
  "M10": "球状星团M10",
  "M100": "螺旋星系M100",
  "M101": "风车星系",
  "M102": "星系M102",
  "M103": "疏散星团M103",
  "M104": "草帽星系",
  "M105": "椭圆星系M105",
  "M106": "螺旋星系M106",
  "M107": "球状星团M107",
  "M108": "梭状星系M108",
  "M109": "螺旋星系M109",
  "M11": "野鸭星团",
  "M110": "仙女座星系M110",
  "M12": "球状星团M12",
  "M13": "武仙座球状星团",
  "M14": "球状星团M14",
  "M15": "球状星团M15",
  "M16": "鹰状星云",
  "M17": "欧米茄星云",
  "M18": "疏散星团M18",
  "M19": "球状星团M19",
  "M2": "球状星团M2",
  "M20": "三叶星云",
  "M21": "疏散星团M21",
  "M22": "球状星团M22",
  "M23": "疏散星团M23",
  "M24": "小人马恒星云",
  "M25": "疏散星团M25",
  "M26": "疏散星团M26",
  "M27": "哑铃星云",
  "M28": "球状星团M28",
  "M29": "疏散星团M29",
  "M3": "球状星团M3",
  "M30": "球状星团M30",
  "M31": "仙女座星系",
  "M32": "仙女座星系M32",
  "M33": "三角座星系",
  "M34": "疏散星团M34",
  "M35": "疏散星团M35",
  "M36": "疏散星团M36",
  "M37": "疏散星团M37",
  "M38": "疏散星团M38",
  "M39": "疏散星团M39",
  "M4": "球状星团M4",
  "M40": "双星M40",
  "M41": "疏散星团M41",
  "M42": "猎户座大星云",
  "M43": "猎户座M43",
  "M44": "鬼星团",
  "M45": "昴星团",
  "M46": "疏散星团M46",
  "M47": "疏散星团M47",
  "M48": "疏散星团M48",
  "M49": "室女座星系M49",
  "M5": "球状星团M5",
  "M50": "疏散星团M50",
  "M51": "涡状星系",
  "M52": "疏散星团M52",
  "M53": "球状星团M53",
  "M54": "球状星团M54",
  "M55": "球状星团M55",
  "M56": "球状星团M56",
  "M57": "环状星云",
  "M58": "室女座星系M58",
  "M59": "室女座星系M59",
  "M6": "蝴蝶星团",
  "M60": "室女座星系M60",
  "M61": "螺旋星系M61",
  "M62": "球状星团M62",
  "M63": "向日葵星系",
  "M64": "黑眼星系",
  "M65": "螺旋星系M65",
  "M66": "螺旋星系M66",
  "M67": "疏散星团M67",
  "M68": "球状星团M68",
  "M69": "球状星团M69",
  "M7": "托勒密星团",
  "M70": "球状星团M70",
  "M71": "球状星团M71",
  "M72": "球状星团M72",
  "M73": "星群M73",
  "M74": "螺旋星系M74",
  "M75": "球状星团M75",
  "M76": "小哑铃星云",
  "M77": "螺旋星系M77",
  "M78": "猎户座反射星云",
  "M79": "球状星团M79",
  "M8": "礁湖星云",
  "M80": "球状星团M80",
  "M81": "波德星系",
  "M82": "雪茄星系",
  "M83": "南风车星系",
  "M84": "室女座星系M84",
  "M85": "室女座星系M85",
  "M86": "室女座星系M86",
  "M87": "室女座星系M87",
  "M88": "螺旋星系M88",
  "M89": "室女座星系M89",
  "M9": "球状星团M9",
  "M90": "螺旋星系M90",
  "M91": "螺旋星系M91",
  "M92": "球状星团M92",
  "M93": "疏散星团M93",
  "M94": "螺旋星系M94",
  "M95": "螺旋星系M95",
  "M96": "螺旋星系M96",
  "M97": "猫头鹰星云",
  "M98": "螺旋星系M98",
  "M99": "螺旋星系M99",
  "Messier 10": "球状星团M10",
  "Messier 100": "螺旋星系M100",
  "Messier 102": "星系M102",
  "Messier 103": "疏散星团M103",
  "Messier 105": "椭圆星系M105",
  "Messier 106": "螺旋星系M106",
  "Messier 107": "球状星团M107",
  "Messier 108": "梭状星系M108",
  "Messier 109": "螺旋星系M109",
  "Messier 110": "仙女座星系M110",
  "Messier 12": "球状星团M12",
  "Messier 14": "球状星团M14",
  "Messier 15": "球状星团M15",
  "Messier 18": "疏散星团M18",
  "Messier 19": "球状星团M19",
  "Messier 2": "球状星团M2",
  "Messier 21": "疏散星团M21",
  "Messier 22": "球状星团M22",
  "Messier 23": "疏散星团M23",
  "Messier 25": "疏散星团M25",
  "Messier 26": "疏散星团M26",
  "Messier 28": "球状星团M28",
  "Messier 29": "疏散星团M29",
  "Messier 3": "球状星团M3",
  "Messier 30": "球状星团M30",
  "Messier 32": "仙女座星系M32",
  "Messier 34": "疏散星团M34",
  "Messier 35": "疏散星团M35",
  "Messier 36": "疏散星团M36",
  "Messier 37": "疏散星团M37",
  "Messier 38": "疏散星团M38",
  "Messier 39": "疏散星团M39",
  "Messier 4": "球状星团M4",
  "Messier 40": "双星M40",
  "Messier 41": "疏散星团M41",
  "Messier 43": "猎户座M43",
  "Messier 46": "疏散星团M46",
  "Messier 47": "疏散星团M47",
  "Messier 48": "疏散星团M48",
  "Messier 49": "室女座星系M49",
  "Messier 5": "球状星团M5",
  "Messier 50": "疏散星团M50",
  "Messier 52": "疏散星团M52",
  "Messier 53": "球状星团M53",
  "Messier 54": "球状星团M54",
  "Messier 55": "球状星团M55",
  "Messier 56": "球状星团M56",
  "Messier 58": "室女座星系M58",
  "Messier 59": "室女座星系M59",
  "Messier 60": "室女座星系M60",
  "Messier 61": "螺旋星系M61",
  "Messier 62": "球状星团M62",
  "Messier 65": "螺旋星系M65",
  "Messier 66": "螺旋星系M66",
  "Messier 67": "疏散星团M67",
  "Messier 68": "球状星团M68",
  "Messier 69": "球状星团M69",
  "Messier 70": "球状星团M70",
  "Messier 71": "球状星团M71",
  "Messier 72": "球状星团M72",
  "Messier 73": "星群M73",
  "Messier 74": "螺旋星系M74",
  "Messier 75": "球状星团M75",
  "Messier 77": "螺旋星系M77",
  "Messier 79": "球状星团M79",
  "Messier 80": "球状星团M80",
  "Messier 84": "室女座星系M84",
  "Messier 85": "室女座星系M85",
  "Messier 86": "室女座星系M86",
  "Messier 87": "室女座星系M87",
  "Messier 88": "螺旋星系M88",
  "Messier 89": "室女座星系M89",
  "Messier 9": "球状星团M9",
  "Messier 90": "螺旋星系M90",
  "Messier 91": "螺旋星系M91",
  "Messier 92": "球状星团M92",
  "Messier 93": "疏散星团M93",
  "Messier 94": "螺旋星系M94",
  "Messier 95": "螺旋星系M95",
  "Messier 96": "螺旋星系M96",
  "Messier 98": "螺旋星系M98",
  "Messier 99": "螺旋星系M99",
  "Orion Reflection Nebula": "猎户座反射星云",
  "Small Sagittarius Star Cloud": "小人马恒星云",

  // === 其他天文术语 ===
  "star": "恒星",
  "planet": "行星",
  "dwarf planet": "矮行星",
  "asteroid": "小行星",
  "comet": "彗星",
  "nebula": "星云",
  "galaxy": "星系",
  "cluster": "星团",
  "globular cluster": "球状星团",
  "open cluster": "疏散星团",
  "planetary nebula": "行星状星云",
  "supernova remnant": "超新星遗迹",
  "constellation": "星座",
  "satellite": "卫星",
  "International Space Station": "国际空间站",
  "Milky Way": "银河"
};
